#!/bin/bash

# INIT-DAEMONS
xsetroot -cursor_name left_ptr &
sxhkd &
picom --experimental-backends &
dunst &

# Replace caps lock with Esc
# setxkbmap -option caps:escape

#### MONITORS ####
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

external_monitor=$(xrandr --query | grep 'VGA1')

if [[ $external_monitor = VGA1\ connected* ]]; then
    xrandr --output VGA1 --primary --mode 1366x768 --rotate normal --output LVDS1 --mode 1920x1080 --rotate normal --above LVDS1
        bspc monitor VGA1 -d 1 2 3 4 5
        bspc monitor eDP-1 -d 6 7 8 9 0
else
	xrandr --output eDP-1 --auto
	bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 0
fi

#### BSPWM configuration ####
bspc config border_radius                 40
bspc config window_gap 			  		  10
bspc config top_padding                   24
bspc config top_monocle_padding			  0
bspc config border_width 		  		  2
bspc config bottom_padding                24
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                false
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config paddingless_monocle  	  	  true
bspc config focus_follows_pointer         true
bspc config ignore_ewmh_focus 		  	  true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# Colors
# bspc config active_border_color \#665c54
# bspc config focused_border_color \#665c54
# bspc config normal_border_color \#363836
bspc config active_border_color '#6099B1'
bspc config normal_border_color '#0C1115'
bspc config focused_border_color '#6099B1'

# Rules

bspc rule -a init_brave desktop='^2'
bspc rule -a discord desktop='^8'
bspc rule -a feh state='floating'
bspc rule -a mpv state='floating'
bspc rule -a Zathura state='tiled'
bspc rule -a Pavucontrol state='floating'
bspc rule -a flameshot state='floating'
bspc rule -a *:SPLASH state=floating
bspc desktop -f 1

# AUTOSTART
setxkbmap -model pc104 -layout us,mn -option grp:alt_shift_toggle & 
xbacklight -set 90 & 
feh --bg-fill ~/.wallpaper/mechanical/mechanical-key_2K.jpg &
~/.config/polybar/launch.sh &
~/.config/bspwm/autostart &
pidof bspswallow || bspswallow &
xrdb ~/.Xresources & 
flameshot & 
