version: "3"

services:
  react:
    build:
      context: .
      dockerfile: react.dockerfile
    ports:
      - "3000:3000"
    container_name: react
    stdin_open: true
    volumes:
      - ./src:/usr/src/app/src
      - /usr/src/app/src/node_modules
